# Staging UI configuration
servers:
  web:
    - 100.57.71.7

ssh:
  keys:
    - /home/thimmaiah/.ssh/foxall.pem

proxy:
  ssl: false
  host: 100.57.71.7.nip.io
  app_port: 80

builder:
  args:
    VITE_API_URL: http://100.57.71.7
